apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
        - name: migrate
          image: fintech-backend:latest
          command: ["python", "-m", "alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: fintech-config
            - secretRef:
                name: fintech-secrets
          env:
            - name: DATABASE_URL
              value: "postgresql+psycopg://postgres:postgres@postgres:5432/fintech"
      containers:
        - name: worker
          image: fintech-backend:latest
          command: ["python", "-m", "app.workers.loan_worker"]
          envFrom:
            - configMapRef:
                name: fintech-config
            - secretRef:
                name: fintech-secrets
          env:
            - name: DATABASE_URL
              value: "postgresql+psycopg://postgres:postgres@postgres:5432/fintech"
