"""add risk decisions table.

Revision ID: 37806d469804
Revises: b0aab731fe22
Create Date: 2026-04-11 02:49:11.600171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37806d469804'
down_revision: Union[str, Sequence[str], None] = 'b0aab731fe22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_application_id', sa.String(length=36), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_possible_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('evaluated_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_decisions_country_code'), 'risk_decisions', ['country_code'], unique=False)
    op.create_index(op.f('ix_risk_decisions_loan_application_id'), 'risk_decisions', ['loan_application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_decisions_loan_application_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_country_code'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    # ### end Alembic commands ###
