"""loan application fk fix

Revision ID: a0b7cc607e59
Revises: 7d7f194e50a4
Create Date: 2026-04-10 04:42:54.822158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b7cc607e59'
down_revision: Union[str, Sequence[str], None] = '7d7f194e50a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_queue', sa.Column('loan_application_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'job_queue', 'loan_applications', ['loan_application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_queue', type_='foreignkey')
    op.drop_column('job_queue', 'loan_application_id')
    # ### end Alembic commands ###
