"""add_pending_review_status_fixed

Revision ID: b0aab731fe22
Revises: acef7c55ce0d
Create Date: 2026-04-10 19:09:57.133387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0aab731fe22'
down_revision: Union[str, Sequence[str], None] = 'acef7c55ce0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE application_status ADD VALUE IF NOT EXISTS 'pending_review'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
